INSERT INTO compliment (description) VALUES ('Ты всегда знаешь, как меня удивить.');
INSERT INTO compliment (description) VALUES ('Глядя на тебя, понимаешь, что спорт — это сила');
INSERT INTO compliment (description) VALUES ('Потрясающая фигура! Тебя легко принять за фитнес-тренера или спортсменку');
INSERT INTO compliment (description) VALUES ('Прости, засмотрелся на тебя и потерял мысль. Ты не могла бы повторить все еще раз?');
INSERT INTO compliment (description) VALUES ('Если быть красивой считается преступлением, то тебя объявят виновной.');
INSERT INTO compliment (description) VALUES ('Я вижу столько тепла в твоих глазах.');
INSERT INTO compliment (description) VALUES ('Не переставай улыбаться, твоя улыбка обворожительна!');
INSERT INTO compliment (description) VALUES ('Мне нравится твой стиль.');
INSERT INTO compliment (description) VALUES ('Это платье идеально сидит на тебе. Я ему даже завидую.');
INSERT INTO compliment (description) VALUES ('Ты очень вкусно пахнешь.');
INSERT INTO compliment (description) VALUES ('Твой смех очаровывает!');
INSERT INTO compliment (description) VALUES ('Я очень сильно ценю тебя.');
INSERT INTO compliment (description) VALUES ('Ты прекрасный слушатель.');
INSERT INTO compliment (description) VALUES ('С тобой гораздо интереснее общаться, чем с моими сверстниками!');
INSERT INTO compliment (description) VALUES ('Ты очень добра к людям вокруг тебя.');
INSERT INTO compliment (description) VALUES ('У тебя всегда самые лучшие идеи.');
INSERT INTO compliment (description) VALUES ('Ты очень талантливая и креативная девушка');
INSERT INTO compliment (description) VALUES ('Твой голос очень мелодичный и волнующий.');
INSERT INTO compliment (description) VALUES ('У тебя безукоризненные манеры.');
INSERT INTO compliment (description) VALUES ('Ты отлично владеешь искусством оказываться в нужное время в нужном месте!');
INSERT INTO compliment (description) VALUES ('Как тебе удается находить выход из безвыходных ситуаций?!');
INSERT INTO compliment (description) VALUES ('Я хотел бы встретить тебя еще в детстве.');
INSERT INTO compliment (description) VALUES ('Ты заслуживаешь объятия прямо сейчас.');
INSERT INTO compliment (description) VALUES ('Ты являешься прекрасным примером для других.');
INSERT INTO compliment (description) VALUES ('Ты всегда можешь подобрать правильные слова.');
INSERT INTO compliment (description) VALUES ('Мне очень нравятся твои причуды.');
INSERT INTO compliment (description) VALUES ('Мне нравится гулять с тобой.');
INSERT INTO compliment (description) VALUES ('С тобой я могу говорить обо всем.');
INSERT INTO compliment (description) VALUES ('С тобой мне всегда очень комфортно.');
INSERT INTO compliment (description) VALUES ('Я благодарен за то, что ты есть.');
INSERT INTO compliment (description) VALUES ('Даже когда ты рядом, мне кажется, что тебя не хватает.');
INSERT INTO compliment (description) VALUES ('Ты понимаешь меня настолько хорошо, как будто читаешь мои мысли.');
INSERT INTO compliment (description) VALUES ('Просто проводить время с умной, интеллигентной девушкой уже приносит незабываемые минуты радости.');
INSERT INTO compliment (description) VALUES ('Ты классная собеседница. Когда общаюсь с тобой, даже не замечаю, как пролетает время.');
INSERT INTO compliment (description) VALUES ('Ты невероятна, когда не боишься быть собой.');
INSERT INTO compliment (description) VALUES ('Твоя действия говорят больше, чем слова.');
INSERT INTO compliment (description) VALUES ('Меня поражает твоя открытость и искренность.');
INSERT INTO compliment (description) VALUES ('Я полностью обезоружен твоим остроумием.');
INSERT INTO compliment (description) VALUES ('У меня мурашки от тебя.');
INSERT INTO compliment (description) VALUES ('Ты как магнит притягиваешь к себе.');
INSERT INTO compliment (description) VALUES ('С тобой очень легко и приятно говорить, ты умеешь располагать к себе парней.');
INSERT INTO compliment (description) VALUES ('Вот смотрю на тебя и понимаю, что в человеке может быть прекрасна душа, тело и мысли.');
INSERT INTO compliment (description) VALUES ('Ты вдохновила меня на …');
INSERT INTO compliment (description) VALUES ('Это так мило с твоей стороны.');
INSERT INTO compliment (description) VALUES ('Ты исполняешь эту песню в разы лучше этого исполнителя!');
INSERT INTO compliment (description) VALUES ('Рядом с тобой я могу быть самим собой.');
INSERT INTO compliment (description) VALUES ('Ты важна для меня.');
INSERT INTO compliment (description) VALUES ('Ты даришь мне вдохновение в жизни, которое ранее меня не посещало. Классно, что я встретил тебя, очаровательная муза!');
INSERT INTO compliment (description) VALUES ('Благодаря тебе я поверил в то, что действительно бывают родственные души.');
INSERT INTO compliment (description) VALUES ('Мне очень важно выслушать твое мнение.');
INSERT INTO compliment (description) VALUES ('Обожаю твои милые странности.');
INSERT INTO compliment (description) VALUES ('Ты потрясающий друг!');
INSERT INTO compliment (description) VALUES ('Ты – уникальная! В тебя нельзя не влюбиться.');
INSERT INTO compliment (description) VALUES ('Ты – мой антидепрессант!');
INSERT INTO compliment (description) VALUES ('Всякий раз, когда мне грустно, мысль о тебе сразу поднимает настроение.');
INSERT INTO compliment (description) VALUES ('Доверяю твоей интуиции.');
INSERT INTO compliment (description) VALUES ('Ты понимаешь меня лучше всех на свете.');
INSERT INTO compliment (description) VALUES ('Ты даешь мне уверенность в себе и всегда меня поддерживаешь. Ты моя надежда и любовь.');
INSERT INTO compliment (description) VALUES ('Часто выступаешь публично? У тебя отлично получается!');
INSERT INTO compliment (description) VALUES ('У тебя огромный творческий потенциал! Ты можешь сотворить шедевр в каждой сфере жизни!');
INSERT INTO compliment (description) VALUES ('Ты удивительная девушка, которая может служить примером для всех остальных.');
INSERT INTO compliment (description) VALUES ('Это потрясающе, что ты всегда стремишься к саморазвитию.');
INSERT INTO compliment (description) VALUES ('Твой творческий потенциал кажется безграничным.');
INSERT INTO compliment (description) VALUES ('Ты на самом деле знаешь кто ты и чего хочешь.');
INSERT INTO compliment (description) VALUES ('Ты знаешь себе цену.');
INSERT INTO compliment (description) VALUES ('Ты признаешь свои ошибки и пытаешься их исправить.');
INSERT INTO compliment (description) VALUES ('Ты всегда изучаешь новые вещи и пытаешься развиваться — это потрясающе.');
INSERT INTO compliment (description) VALUES ('Я не сумел бы завершить это дело без твоей помощи.');
INSERT INTO compliment (description) VALUES ('Много читаешь? Порекомендуешь что-нибудь? Мне почему-то кажется, что ты сразу же угадаешь книгу, которая мне понравится.');
INSERT INTO compliment (description) VALUES ('Ты очень хорошо готовишь.');
INSERT INTO compliment (description) VALUES ('Если бы я сейчас поехал в путешествие, то взял бы с собой только тебя.');
INSERT INTO compliment (description) VALUES ('Ты подарок для окружающих.');
INSERT INTO compliment (description) VALUES ('У тебя безупречные манеры.');
INSERT INTO compliment (description) VALUES ('Ты красиво смеешься.');
INSERT INTO compliment (description) VALUES ('Ты очень дорога мне.');
INSERT INTO compliment (description) VALUES ('Ты само совершенство.');
INSERT INTO compliment (description) VALUES ('Ты должна гордиться собой.');
INSERT INTO compliment (description) VALUES ('У тебя отличное чувство юмора.');
INSERT INTO compliment (description) VALUES ('Ты меня вдохновляешь.');
INSERT INTO compliment (description) VALUES ('Ты лучик солнца в пасмурный день.');
INSERT INTO compliment (description) VALUES ('Ты отличный слушатель.');
INSERT INTO compliment (description) VALUES ('Ты, как всегда, выглядишь потрясающе, даже в тренировочных штанах.');
INSERT INTO compliment (description) VALUES ('Этот цвет идеально подходит тебе.');
INSERT INTO compliment (description) VALUES ('В нужный момент ты всегда говоришь именно то, что мне нужно услышать.');
INSERT INTO compliment (description) VALUES ('Ты делаешь меня счастливым.');
INSERT INTO compliment (description) VALUES ('Я могу довериться тебе во всем.');
INSERT INTO compliment (description) VALUES ('Ты невероятная девушка! Ты не боишься быть естественной и настоящей.');
INSERT INTO compliment (description) VALUES ('Мир кажется ярче, когда ты рядом.');
INSERT INTO compliment (description) VALUES ('Ты замечательная.');
INSERT INTO compliment (description) VALUES ('У тебя очень красивые глаза.');
INSERT INTO compliment (description) VALUES ('Ты очень добра к окружающим тебя людям.');
INSERT INTO compliment (description) VALUES ('Ты единственная в своем роде!');
INSERT INTO compliment (description) VALUES ('Ты всегда находишь что-то особенное в самых обычных вещах.');
INSERT INTO compliment (description) VALUES ('Ты – мой свет.');
INSERT INTO compliment (description) VALUES ('Ты отличный пример для окружающих.');
INSERT INTO compliment (description) VALUES ('Ты всегда знаешь, что сказать.');
INSERT INTO compliment (description) VALUES ('Твоим родителям нужно дать медаль за отличное воспитание дочери.');
INSERT INTO compliment (description) VALUES ('У тебя очень приятный голос.');
INSERT INTO compliment (description) VALUES ('Ты подобна глотку свежего воздуха.');
INSERT INTO compliment (description) VALUES ('Твое имя очень подходит твоей личности.');
INSERT INTO compliment (description) VALUES ('Тебя, наверное, очень любят дети.');
INSERT INTO compliment (description) VALUES ('Ты очень позитивная: окружающие тебя люди все время улыбаются.');
INSERT INTO compliment (description) VALUES ('У тебя отличная фигура');
INSERT INTO compliment (description) VALUES ('Ты действительно очень особенная.');
INSERT INTO compliment (description) VALUES ('Спасибо за то, что ты есть.');
INSERT INTO compliment (description) VALUES ('Тебе известны такие знаменитости, как Дженнифер Энистон, Анджелина Джоли, Джессика Билл?! Так вот, они не сравнятся с тобой!');
INSERT INTO compliment (description) VALUES ('Твоя улыбка заставляет биться моё сердце чаще.');
INSERT INTO compliment (description) VALUES ('Я не верил в любовь, пока не встретил тебя.');
INSERT INTO compliment (description) VALUES ('Время останавливается, когда я с тобой.');
INSERT INTO compliment (description) VALUES ('Ты ярче всех звезд на небе.');
INSERT INTO compliment (description) VALUES ('День, когда мы встретились, был лучшим в моей жизни.');
INSERT INTO compliment (description) VALUES ('Ни одна из других девушек не может сравниться с тобой.');
INSERT INTO compliment (description) VALUES ('Ты самый удивительный человек, которого я когда-либо знал.');
INSERT INTO compliment (description) VALUES ('Я не могу не улыбнуться, когда думаю о тебе.');
INSERT INTO compliment (description) VALUES ('Ты меня понимаешь, как никто другой.');
INSERT INTO compliment (description) VALUES ('Один взгляд на тебя помогает мне забыть обо всех моих проблемах.');
INSERT INTO compliment (description) VALUES ('Твоя улыбка — это солнце, которое светит сквозь облака в мрачный день.');
INSERT INTO compliment (description) VALUES ('Твои губы на вкус сладкие как конфеты.');
INSERT INTO compliment (description) VALUES ('Для меня ты самая прекрасная девушка в мире.');
INSERT INTO compliment (description) VALUES ('Ужин, который ты сделала для меня, был восхитителен.');
INSERT INTO compliment (description) VALUES ('Мне нравится твоё чувство стиля.');
INSERT INTO compliment (description) VALUES ('Твои волосы выглядят потрясающе.');
INSERT INTO compliment (description) VALUES ('Ты очень приятно пахнешь.');
INSERT INTO compliment (description) VALUES ('Мне нравится твоё платье. Выглядит очень женственно.');
INSERT INTO compliment (description) VALUES ('Я скучаю по твоим поцелуям и объятиям!');
INSERT INTO compliment (description) VALUES ('Ты выглядишь ещё лучше без макияжа.');
INSERT INTO compliment (description) VALUES ('Каждый раз, когда я с тобой, ты заставляешь меня чувствовать себя таким особенным.');
INSERT INTO compliment (description) VALUES ('Цвета кажутся ярче, когда ты рядом.');
INSERT INTO compliment (description) VALUES ('Быть одному приятно, но быть наедине с тобой гораздо лучше.');
INSERT INTO compliment (description) VALUES ('Кажется, что время замирает, когда я с тобой.');
INSERT INTO compliment (description) VALUES ('Я доверяю тебе всё, что у меня есть.');
INSERT INTO compliment (description) VALUES ('Я старался изо всех сил, но не смог перестать думать о тебе.');
INSERT INTO compliment (description) VALUES ('Я ждал всю свою жизнь, чтобы встретить такую девушку, как ты.');
INSERT INTO compliment (description) VALUES ('Я люблю каждое утро просыпаться вместе с тобой и засыпать вместе с тобой каждую ночь.');
INSERT INTO compliment (description) VALUES ('Ты моя и только моя. Все права защищены.');
INSERT INTO compliment (description) VALUES ('Ты ангел, посланный прямо с небес.');
INSERT INTO compliment (description) VALUES ('Мой мир без тебя бессмыслен.');
INSERT INTO compliment (description) VALUES ('Я получаю удовольствие от общения с тобой: ты веселая и умная.');
INSERT INTO compliment (description) VALUES ('Ты прекрасна.');
INSERT INTO compliment (description) VALUES ('Ты такая понимающая.');
INSERT INTO compliment (description) VALUES ('Ты будешь отличной матерью.');
INSERT INTO compliment (description) VALUES ('Я хочу состариться вместе с тобой.');
INSERT INTO compliment (description) VALUES ('Ты очень талантливая и креативная девушка.');
INSERT INTO compliment (description) VALUES ('Ты – женщина моей мечты!');
INSERT INTO compliment (description) VALUES ('Я очень богатый человек, потому что ты – моя жена.');
INSERT INTO compliment (description) VALUES ('Я буду любить тебя вечно.');
INSERT INTO compliment (description) VALUES ('Ты очень фотогеничная.');
INSERT INTO compliment (description) VALUES ('Ты классно танцуешь.');
INSERT INTO compliment (description) VALUES ('Твое самообладание восхищает.');
INSERT INTO compliment (description) VALUES ('Ты – кладезь полезной информации.');
INSERT INTO compliment (description) VALUES ('Ты очень позитивный человек.');
INSERT INTO compliment (description) VALUES ('Ну это преступление – быть такой роскошной.');
INSERT INTO compliment (description) VALUES ('Ты готовишь даже лучше моей мамы.');
INSERT INTO compliment (description) VALUES ('Обожаю твое чувство юмора.');
INSERT INTO compliment (description) VALUES ('Ты сногсшибательна и обворожительна!');
INSERT INTO compliment (description) VALUES ('Я теряю связь с реальностью, когда смотрю на тебя.');
INSERT INTO compliment (description) VALUES ('Ты достойна тысячи комплиментов.');
INSERT INTO compliment (description) VALUES ('Неотразима, как всегда!');
INSERT INTO compliment (description) VALUES ('Ты – моя любовь и моя гордость.');
INSERT INTO compliment (description) VALUES ('В тебе столько нежности, счастья и чуткости!');
INSERT INTO compliment (description) VALUES ('Очаровашка, глаз не могу отвести!');
INSERT INTO compliment (description) VALUES ('Ты, пока шла ко мне, толпу поклонников за собой не привела?');
INSERT INTO compliment (description) VALUES ('Блестяще выглядишь!');
INSERT INTO compliment (description) VALUES ('С такой голливудской улыбкой только в кино сниматься.');
INSERT INTO compliment (description) VALUES ('Сегодня ты затмишь всех.');
INSERT INTO compliment (description) VALUES ('Твой главный козырь – независимость.');
INSERT INTO compliment (description) VALUES ('Какая ты роскошная, сразу видно – настоящая женщина!');
INSERT INTO compliment (description) VALUES ('Ты – мой самый дорогой подарок от жизни!');
INSERT INTO compliment (description) VALUES ('Обворожительна, словно королева из сказки.');
INSERT INTO compliment (description) VALUES ('Эта искренняя улыбка сводит меня с ума.');
INSERT INTO compliment (description) VALUES ('Манящая, завораживающая… Не волшебница, случайно?');
INSERT INTO compliment (description) VALUES ('Стильная и привлекательная леди, так держать!');
INSERT INTO compliment (description) VALUES ('Легка как облачко!');
INSERT INTO compliment (description) VALUES ('Ухоженна и привлекательна!');
INSERT INTO compliment (description) VALUES ('Сладкая, как персик!');
INSERT INTO compliment (description) VALUES ('Глаза, словно магниты.');
INSERT INTO compliment (description) VALUES ('Приближаясь к тебе, ощущаю магнетизм.');
INSERT INTO compliment (description) VALUES ('У тебя отличный вкус и чувство стиля!');
INSERT INTO compliment (description) VALUES ('Вежливая и культурная.');
INSERT INTO compliment (description) VALUES ('Статная, будто из королевской семьи.');
INSERT INTO compliment (description) VALUES ('Мне нравится, что ты — леди.');
INSERT INTO compliment (description) VALUES ('У тебя такие разносторонние интересы!');
INSERT INTO compliment (description) VALUES ('Твои шутки так оригинальны!');
INSERT INTO compliment (description) VALUES ('Ради тебя могу совершить 1000 безумств.');
INSERT INTO compliment (description) VALUES ('Ты такая открытая, честная и простая.');
INSERT INTO compliment (description) VALUES ('Ты умеешь видеть необычное в простых вещах.');
INSERT INTO compliment (description) VALUES ('Умеешь выделяться из серой массы.');
INSERT INTO compliment (description) VALUES ('Люблю твои тонкие манеры и королевскую воспитанность.');
INSERT INTO compliment (description) VALUES ('Девушка с изюминкой.');
INSERT INTO compliment (description) VALUES ('У тебя незаурядная, яркая внешность.');
INSERT INTO compliment (description) VALUES ('Бесподобная фигура.');
INSERT INTO compliment (description) VALUES ('Ты позитивная и искрометная.');
INSERT INTO compliment (description) VALUES ('Умеешь выслушать и дать дельный совет.');
INSERT INTO compliment (description) VALUES ('Увидев раз, тебя невозможно забыть.');
INSERT INTO compliment (description) VALUES ('Ты та самая, о которой я думаю каждую минуту.');
INSERT INTO compliment (description) VALUES ('Ты для меня самая особенная и незаменимая.');
INSERT INTO compliment (description) VALUES ('Ты была первая и единственная в очереди за красотой?');
INSERT INTO compliment (description) VALUES ('Люблю этот игривый живой огонек в твоих глазах!');
INSERT INTO compliment (description) VALUES ('Один раз тебя увидев, спокойно уснуть уже не получится.');
INSERT INTO compliment (description) VALUES ('Завидую себе, что отхватил такую красотку.');
INSERT INTO compliment (description) VALUES ('От мамы и папы ты взяла лучшее и получилась несравненной!');
INSERT INTO compliment (description) VALUES ('Передо мной все, о чем я мечтал!');
INSERT INTO compliment (description) VALUES ('Твоя внешность так прекрасна, что я бы писал с тебя картины, если бы был художником.');
INSERT INTO compliment (description) VALUES ('Взгляд твоих красивых глаз заставил меня забыть о том, что я хотел сказать и сделать.');
INSERT INTO compliment (description) VALUES ('Перфекционисты бы получили настоящее удовлетворение, если бы они созерцали твою красоту.');
INSERT INTO compliment (description) VALUES ('В отличие от многих девушек, ты без макияжа выглядишь замечательно. Полюбуюсь твоей природной красотой.');
INSERT INTO compliment (description) VALUES ('Когда я смотрю на такую красотку, мое сердце делает сальто.');
INSERT INTO compliment (description) VALUES ('С речью все нормально. Просто, когда вижу милую девушку, мой язык начинает произносить странные звуки.');
INSERT INTO compliment (description) VALUES ('Не могу оторвать глаз от твоей фигуры. Она же идеальна!');
INSERT INTO compliment (description) VALUES ('Чем больше я задумываюсь, какой должна быть идеальная девушка, тем чаще вспоминаю тебя.');
INSERT INTO compliment (description) VALUES ('Ты словно Богиня, сошедшая с небес на землю.');
INSERT INTO compliment (description) VALUES ('Ты не пробовала участвовать в конкурсах красоты? Уверен, заняла бы призовое место.');
INSERT INTO compliment (description) VALUES ('Ты такая роскошная, что у меня в голове обычные строчки складываются в стихи в твою честь.');
INSERT INTO compliment (description) VALUES ('Переплюнуть тебя по красоте сможет разве что твоя дочь.');
INSERT INTO compliment (description) VALUES ('На фотографии ты красива, но она передает только красоту внешнюю. Внутри ты еще прекрасней.');
INSERT INTO compliment (description) VALUES ('Для меня уже незабываемо, что я провожу время с милой и интеллигентной девушкой.');
INSERT INTO compliment (description) VALUES ('Прости, что «завис», я слышу все, что ты говоришь. Просто не могу тобой налюбоваться.');
INSERT INTO compliment (description) VALUES ('Я у тебя многому научился. Выдержке, терпению и настойчивости.');
INSERT INTO compliment (description) VALUES ('Когда мы с тобой болтаем, времени будто не существует.');
INSERT INTO compliment (description) VALUES ('Твои пальцы очень нежные. Когда ты ко мне прикасаешься, вся боль уходит.');
INSERT INTO compliment (description) VALUES ('Ничего в себе не меняй, ведь для меня ты идеальна.');
INSERT INTO compliment (description) VALUES ('Ты меня понимаешь как никто другой, будто читаешь мои мысли. Это сводит меня с ума!');
INSERT INTO compliment (description) VALUES ('Мне нравится, что ты знаешь, чего хочешь добиться в жизни. Ты целеустремленная девушка, планирующая и добивающаяся своего.');
INSERT INTO compliment (description) VALUES ('Обожаю твое умение понять мужчину и поддержать разговор.');
INSERT INTO compliment (description) VALUES ('Мне нравится в тебе все от и до. От легкой походки до умения одеваться, от умения говорить и выражать мысли, до тактичных и смелых идей.');
INSERT INTO compliment (description) VALUES ('Я о такой девушке и не мечтал. Ведь по сравнению с действительностью мечты оказались ничтожными.');
INSERT INTO compliment (description) VALUES ('Знаешь почему я самый счастливый человек? У меня есть ты!');
INSERT INTO compliment (description) VALUES ('Только с тобой я могу быть тем, кто я есть на самом деле. Не лукавя и не притворяясь.');
INSERT INTO compliment (description) VALUES ('Я думал, что бывают только умные или только красивые. Ты доказала на своем примере, что в одном человеке может сочетаться и то, и другое.');
INSERT INTO compliment (description) VALUES ('Надо поблагодарить твоих родителей за то, что они сотворили настоящее чудо – тебя.');
INSERT INTO compliment (description) VALUES ('Когда мужчины оборачиваются и провожают тебя взглядом, я не ревную. Я горжусь, что ты со мной!');
INSERT INTO compliment (description) VALUES ('Когда я тебя увидел, то понял, что естественная красота может быть удивительной и прекрасной.');
INSERT INTO compliment (description) VALUES ('Рядом с тобой мне удалось почувствовать себя настоящим мужчиной.');
INSERT INTO compliment (description) VALUES ('Твой нежный и немного хитрый взгляд заставил сердце бушевать, а руки – дрожать.');
INSERT INTO compliment (description) VALUES ('Я отношусь к тебе слишком трепетно, ведь ты разбудила во мне желание оберегать и защищать.');
INSERT INTO compliment (description) VALUES ('Ты хоть и хрупкая девушка, но быстро отправишь в нокаут своим взглядом.');
INSERT INTO compliment (description) VALUES ('Мудрых женщин, правильно расставляющих жизненные приоритеты, мало. Но я нашел такую.');
INSERT INTO compliment (description) VALUES ('Влюбился с первого взгляда. Боялся, что внешность обманчива. Ты доказала, что я зря боялся.');
INSERT INTO compliment (description) VALUES ('Чувствую себя полностью в твоей власти. Ну и пусть, это приятное рабство.');
INSERT INTO compliment (description) VALUES ('Ты придаешь смысл моей жизни.');
INSERT INTO compliment (description) VALUES ('Я не могу представить свою жизнь без тебя.');
INSERT INTO compliment (description) VALUES ('Как тебе удается всегда выглядеть такой красивой?');
INSERT INTO compliment (description) VALUES ('Мне повезло, что у меня есть ты.');
INSERT INTO compliment (description) VALUES ('Ты всегда знаешь, как меня удивить.');
INSERT INTO compliment (description) VALUES ('Ты — причина, по которой моя жизнь так прекрасна.');
INSERT INTO compliment (description) VALUES ('Когда я вижу тебя, обычный день становится праздником.');
INSERT INTO compliment (description) VALUES ('Я мечтал о тебе прошлой ночью.');
INSERT INTO compliment (description) VALUES ('Даже когда ты рядом, мне кажется, что тебя не хватает.');
INSERT INTO compliment (description) VALUES ('Ты очень вкусно пахнешь.');
INSERT INTO compliment (description) VALUES ('Время, проведенное с тобой — это изюминка моего дня.');
INSERT INTO compliment (description) VALUES ('Я вижу столько тепла в твоих глазах.');
INSERT INTO compliment (description) VALUES ('Ты меня так хорошо понимаешь, что мне кажется, умеешь читать мысли.');
INSERT INTO compliment (description) VALUES ('Я хочу провести с тобой остаток жизни.');
INSERT INTO compliment (description) VALUES ('Я так счастлив, просто проводя с тобой время.');
INSERT INTO compliment (description) VALUES ('Ты не просто моя любимая девушка, но и мой самый лучший друг.');
INSERT INTO compliment (description) VALUES ('Одной твоей улыбки достаточно, чтобы моя грусть просто испарилась.');
INSERT INTO compliment (description) VALUES ('Ты совершенна. Мне нравится в тебе всё.');
INSERT INTO compliment (description) VALUES ('Я чувствую слабость в коленях, когда ты ко мне прикасаешься.');
INSERT INTO compliment (description) VALUES ('Я хочу, чтобы время останавливалось, когда мы с тобой вместе, но оно всегда находит способ пролететь незаметно.');
INSERT INTO compliment (description) VALUES ('Я хотел бы встретить тебя еще в детстве.');
INSERT INTO compliment (description) VALUES ('Твоя милая улыбка сводит меня с ума.');
INSERT INTO compliment (description) VALUES ('Мне так трудно уйти от тебя каждый раз, когда мы прощаемся.');
INSERT INTO compliment (description) VALUES ('Ты моя мечта, которая воплотилась в реальность.');
INSERT INTO compliment (description) VALUES ('Я так сильно тебя люблю, что не смог бы выразить это словами, даже если бы и попробовал.');
INSERT INTO compliment (description) VALUES ('Ты самая красивая девушка, которую я когда-либо встречал.');
INSERT INTO compliment (description) VALUES ('Мне так нравится твоя мягкая кожа, когда я касаюсь ее руками.');
INSERT INTO compliment (description) VALUES ('Я хочу провести остаток своей жизни, чтобы сделать тебя счастливой.');
INSERT INTO compliment (description) VALUES ('Тебе не нужно меняться, потому что я люблю тебя именно такой, какая ты есть.');
INSERT INTO compliment (description) VALUES ('Мне больно видеть тебя грустной.');
INSERT INTO compliment (description) VALUES ('Твои глаза настолько красивы, что я боюсь потеряться в них.');
INSERT INTO compliment (description) VALUES ('Когда ты обнимаешь меня, я ощущаю бабочки в животе.');
INSERT INTO compliment (description) VALUES ('Ты так похожа на красивого ангела, что я боюсь навредить этой красоте, прикасаясь к тебе.');
INSERT INTO compliment (description) VALUES ('Я думаю, что Бога постигло озарение в тот момент, когда создавал тебя, потому что никто больше не был так близок к совершенству.');
INSERT INTO compliment (description) VALUES ('Ты единственное, за что я благодарю свою жизнь.');
INSERT INTO compliment (description) VALUES ('Мне нравится, как твои волосы ощущают мои пальцы, когда я их касаюсь.');
INSERT INTO compliment (description) VALUES ('Мне нравится, когда ты говоришь, что любишь меня, когда целую тебя по телефону.');
INSERT INTO compliment (description) VALUES ('Мне нравится, когда ты находишься в моих объятиях.');
INSERT INTO compliment (description) VALUES ('Каждый мой день начинается с мыслью о тебе, и заканчивается сном о тебе.');
INSERT INTO compliment (description) VALUES ('Ты подарок для окружающих.');
INSERT INTO compliment (description) VALUES ('Ты обалденная.');
INSERT INTO compliment (description) VALUES ('У тебя безупречные манеры.');
INSERT INTO compliment (description) VALUES ('Мне нравится твой стиль.');
INSERT INTO compliment (description) VALUES ('У тебя задорный смех.');
INSERT INTO compliment (description) VALUES ('Я очень сильно ценю тебя.');
INSERT INTO compliment (description) VALUES ('Я не представляю свое существование без тебя.');
INSERT INTO compliment (description) VALUES ('Ты способна затмить солнечный свет своей красотой.');
INSERT INTO compliment (description) VALUES ('Ты заслуживаешь объятий каждую секунду.');
INSERT INTO compliment (description) VALUES ('Ты должна гордиться собой.');
INSERT INTO compliment (description) VALUES ('У тебя потрясающее чувство юмора.');
INSERT INTO compliment (description) VALUES ('Твоя доброта — это бальзам для души каждого, кто знаком с тобой.');
INSERT INTO compliment (description) VALUES ('По шкале от 1 до 10 я ставлю тебе 11.');
INSERT INTO compliment (description) VALUES ('Твой внутренний мир так же прекрасен, как и твоя внешность.');
INSERT INTO compliment (description) VALUES ('Ты очень сильно меня вдохновляешь.');
INSERT INTO compliment (description) VALUES ('Ты словно луч солнца посреди серых будней.');
INSERT INTO compliment (description) VALUES ('Ты видишь только лучшее в других людях.');
INSERT INTO compliment (description) VALUES ('Твоя способность вспомнить всё до малейших деталей впечатляет.');
INSERT INTO compliment (description) VALUES ('Ты прекрасный слушатель.');
INSERT INTO compliment (description) VALUES ('Было бы круто, если бы все люди были похожи на тебя.');
INSERT INTO compliment (description) VALUES ('Это платье идеально сидит на тебе.');
INSERT INTO compliment (description) VALUES ('Я ему даже завидую.');
INSERT INTO compliment (description) VALUES ('Ты позволяешь мне ощущать больше радости в жизни.');
INSERT INTO compliment (description) VALUES ('Ты можешь танцевать так, будто никто не смотрит, но все наблюдают за тобой, потому что потрясающе танцуешь.');
INSERT INTO compliment (description) VALUES ('Ты вкуснее, чем миллион тонн шоколадных конфет.');
INSERT INTO compliment (description) VALUES ('Ты замечательная.');
INSERT INTO compliment (description) VALUES ('Когда мне плохо, ты всегда оказываешь мне поддержку, и я чувствую себя намного лучше.');
INSERT INTO compliment (description) VALUES ('Ты очень добра к людям вокруг тебя.');
INSERT INTO compliment (description) VALUES ('Мне следует чаще благодарить тебя. Так что спасибо тебе.');
INSERT INTO compliment (description) VALUES ('Мое окружение на самом высоком уровне, потому что ты являешься его частью.');
INSERT INTO compliment (description) VALUES ('У тебя всегда самые лучшие идеи.');
INSERT INTO compliment (description) VALUES ('Ты всегда можешь найти что-то особенное в самых обычных вещах.');
INSERT INTO compliment (description) VALUES ('Ты моя свеча в темноте.');
INSERT INTO compliment (description) VALUES ('Ты являешься прекрасным примером для других.');
INSERT INTO compliment (description) VALUES ('Ты всегда можешь подобрать правильные слова.');
INSERT INTO compliment (description) VALUES ('Это потрясающе, что ты всегда стремишься к саморазвитию.');
INSERT INTO compliment (description) VALUES ('Кто тебя воспитывал? Они заслуживают медаль за прекрасно выполненную работу.');
INSERT INTO compliment (description) VALUES ('Ты во всем отлично разбираешься.');
INSERT INTO compliment (description) VALUES ('У тебя очень красивый голос.');
INSERT INTO compliment (description) VALUES ('Людям, которых ты любишь, повезло, что ты присутствуешь в их жизни.');
INSERT INTO compliment (description) VALUES ('Ты словно глоток свежего воздуха.');
INSERT INTO compliment (description) VALUES ('Твой творческий потенциал кажется безграничным.');
INSERT INTO compliment (description) VALUES ('Тебе очень идет твое красивое имя.');
INSERT INTO compliment (description) VALUES ('Мне очень нравятся твои причуды.');
INSERT INTO compliment (description) VALUES ('Это так прекрасно, что все дети любят тебя.');
INSERT INTO compliment (description) VALUES ('Ты моя причина, чтобы улыбаться.');
INSERT INTO compliment (description) VALUES ('Ты очень умная и красивая.');
INSERT INTO compliment (description) VALUES ('У тебя очень грациозная походка.');
INSERT INTO compliment (description) VALUES ('То, как ты ценишь своих близких, просто невероятно.');
INSERT INTO compliment (description) VALUES ('Ты для меня особенная.');
INSERT INTO compliment (description) VALUES ('С тобой я могу говорить обо всем.');
INSERT INTO compliment (description) VALUES ('Я всегда так много узнаю от тебя.');
INSERT INTO compliment (description) VALUES ('Ты очень сексуальная.');
INSERT INTO compliment (description) VALUES ('С тобой мне всегда очень комфортно.');
INSERT INTO compliment (description) VALUES ('Мои друзья без ума от тебя.');
INSERT INTO compliment (description) VALUES ('Я не могу отвести от тебя глаз.');
INSERT INTO compliment (description) VALUES ('Я не могу перестать думать о прошлой ночи.');
INSERT INTO compliment (description) VALUES ('Если бы у меня был миллион долларов, я бы бросил свою работу и проводил каждую секунду с тобой.');